### ISSUE TITLE
alsa(pipewire): seconds high latency with BufferSize::Fixed

### ISSUE THREAD

**Issue by remind-me-later** [RustAudio/cpal#1034]
Hi! I'm using CPAL to make a GB emulator, since the reversal of [this](https://github.com/RustAudio/cpal/commit/5dd648ee8564d3d0ed77c60c95246425dbeebd10) commit I'm getting a very high latency when using Alsa on Linux, the delay is of multiple seconds. I also tried the branch [fix/pipewire-alsa-latency](https://github.com/RustAudio/cpal/tree/fix/pipewire-alsa-latency), but it doesn't solve the issue. Commit `5dd648ee8564d3d0ed77c60c95246425dbeebd10` works like a charm though. All the Cpal code in my project is in the [audio](https://github.com/remind-me-later/Ceres/blob/main/ceres-std/src/audio.rs) file, but this is the [setup](https://github.com/remind-me-later/Ceres/blob/main/ceres-std/src/audio.rs#L241):

```rust
const BUFFER_SIZE: u32 = 512;
const RING_BUFFER_SIZE: usize = BUFFER_SIZE as usize * 4;
const SAMPLE_RATE: i32 = 48000;

let host = cpal::default_host();
let device = host.default_output_device().ok_or(Error::GetOutputDevice)?;

let config = cpal::StreamConfig {
    channels: 2,
    sample_rate: cpal::SampleRate(SAMPLE_RATE as u32),
    buffer_size: cpal::BufferSize::Fixed(BUFFER_SIZE),
};

let error_callback = |err| eprintln!("an AudioError occurred on stream: {err}");
let data_callback = move |buffer: &mut [ProcessSample], _: &_| {
    if let Ok(mut ring) = ring_buffer_clone.lock() {
        ring.write_samples_interleaved(buffer);
    }
};

let stream = device
    .build_output_stream(&config, data_callback, error_callback, None)
    .map_err(|_err| Error::BuildStream)?;
```

As in this [issue](https://github.com/RustAudio/cpal/issues/1029) I'm also using PipeWire. Let me know if you need anything. Thanks!

**Comment by roderickvd** [comment]
Please keep monitoring that PR. I pushed another commit moments ago. Let me know how that goes.

**Comment by remind-me-later** [comment]
The last commit in that PR fixes the latency issue but I get stuttering with `BUFFER_SIZE: u32 = 512`, setting it to 1024 makes it work perfectly.

**Comment by roderickvd** [comment]
I pushed an update to fix a logic error - would be interested to hear if that improves your 512 buffer size.

**Comment by remind-me-later** [comment]
I'm still getting stuttering.

This is the pattern I observe of my ring buffer in the last commit from the fix branch:
```
Samples in buffer: 2048
Samples in buffer: 1395
Samples in buffer: 2048
Samples in buffer: 1518
Samples in buffer: 2048
Samples in buffer: 1516
Samples in buffer: 2048
Samples in buffer: 1517
Samples in buffer: 2048
Samples in buffer: 1516
Samples in buffer: 2048
Samples in buffer: 1516
Samples in buffer: 2048
Samples in buffer: 1516
Samples in buffer: 2048
Samples in buffer: 1516
Samples in buffer: 2048
Samples in buffer: 1516
```

And this is the [working commit](https://github.com/RustAudio/cpal/commit/5dd648ee8564d3d0ed77c60c95246425dbeebd10):
```
Samples in buffer: 2048
Samples in buffer: 1402
Samples in buffer: 1671
Samples in buffer: 1953
Samples in buffer: 1420
Samples in buffer: 1699
Samples in buffer: 1980
Samples in buffer: 1447
Samples in buffer: 1724
Samples in buffer: 2004
Samples in buffer: 1471
Samples in buffer: 1747
Samples in buffer: 1357
Samples in buffer: 1502
Samples in buffer: 1787
Samples in buffer: 1259
Samples in buffer: 1541
Samples in buffer: 1826
Samples in buffer: 1297
Samples in buffer: 1579
Samples in buffer: 1863
```

Since the buffer size is 2048 with 512 samples I think maybe the callback is not draining the buffer fast enough? Making the ring buffer bigger (8192) doesn't seem to improve things:

```
Samples in buffer: 8192
Samples in buffer: 7538
Samples in buffer: 8192
Samples in buffer: 7656
Samples in buffer: 8192
Samples in buffer: 7655
Samples in buffer: 8192
Samples in buffer: 7655
Samples in buffer: 8192
Samples in buffer: 7655
Samples in buffer: 8192
Samples in buffer: 7655
Samples in buffer: 8192
Samples in buffer: 7655
Samples in buffer: 8192
Samples in buffer: 7655
Samples in buffer: 8192
Samples in buffer: 7655
Samples in buffer: 8192
Samples in buffer: 7655
Samples in buffer: 8192
Samples in buffer: 7655
Samples in buffer: 8192
Samples in buffer: 7655
Samples in buffer: 8192
Samples in buffer: 7655
```

Please tell me if this is useful or if there are any other metrics I could share. Thanks!

**Comment by roderickvd** [comment]
I’ll think about it later as I’m away for a few days.

**Comment by remind-me-later** [comment]
Hi again, I was just playing around with commit `e15d1cc70e36d691fc259fcab02ed591a79850f0` and it seems to be working perfectly 😄. Thanks for the patches.

**Comment by roderickvd** [comment]
If I'm understanding you correctly, this should be fixed now that #1033 is merged. Feel free to re-open if not.
